import React from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import { expect, userEvent, within } from 'storybook/test';
import { AILabel, Button, Link } from 'ionbase-ui';

const meta: Meta<typeof AILabel> = {
  title: 'Components/AILabel',
  component: AILabel,
  tags: ['autodocs'],
  args: { 'aria-label': 'About this summary' },
  parameters: {
    docs: {
      description: {
        component:
          'Marks content as generated by AI, and opens what that means: what was generated, from what, and what to check. A Toggletip whose button is the mark — opened on purpose, part of the page, never modal. The explanation is required: a mark with nothing behind it is a claim the system cannot back.\n\nIt labels; it does not detect. `isEdited` says a person has changed the content since.',
      },
    },
  },
  render: (args) => (
    <div style={{ padding: '120px 24px 24px', maxWidth: 480 }}>
      <p className="ion-text-body-sm" style={{ display: 'flex', gap: 8 }}>
        <strong>Summary</strong>
        <AILabel {...args}>
          Written by atlas-m from the last 20 runs. Check the failure counts
          against the Runs tab before sharing.{' '}
          <Link href="#how">How summaries are made</Link>
        </AILabel>
      </p>
      <p className="ion-text-body-sm">
        Support triage ran 1,204 times this week; 3 runs failed on timeouts.
      </p>
      <Button size="sm" variant="tertiary">
        Next
      </Button>
    </div>
  ),
};

export default meta;
type Story = StoryObj<typeof AILabel>;

export const Default: Story = {};
export const Small: Story = { args: { size: 'sm' } };
export const Edited: Story = { args: { isEdited: true } };

const button = (canvas: ReturnType<typeof within>) =>
  canvas.getByRole('button', { name: /^AI/ });

/**
 * The name starts with what is seen, then says what it is about — "AI:
 * About this summary" — and the button is a disclosure.
 */
export const TheNameStartsWithTheMark: Story = {
  play: async ({ canvas }) => {
    const b = button(canvas);
    await expect(b).toHaveAccessibleName('AI: About this summary');
    await expect(b).toHaveTextContent('AI');
    await expect(b).toHaveAttribute('aria-expanded', 'false');
  },
};

/** A click opens the explanation, headed by what the mark means. */
export const OpensTheExplanation: Story = {
  play: async ({ canvas }) => {
    const b = button(canvas);
    await userEvent.click(b);
    await expect(b).toHaveAttribute('aria-expanded', 'true');
    const bubble = document.getElementById(b.getAttribute('aria-controls')!)!;
    await expect(bubble).toHaveAttribute('role', 'status');
    await expect(bubble).toHaveTextContent(/^Generated by AI/);
    await expect(bubble).toHaveTextContent('Written by atlas-m');
    // Focus stays on the mark; the page is not hidden.
    await expect(b).toHaveFocus();
    await expect(bubble).not.toHaveAttribute('aria-modal');
  },
};

/** Tab reaches the link inside; Escape closes and returns to the mark. */
export const TheLinkIsReachable: Story = {
  play: async ({ canvas }) => {
    const b = button(canvas);
    await userEvent.click(b);
    await userEvent.tab();
    await expect(
      canvas.getByRole('link', { name: 'How summaries are made' }),
    ).toHaveFocus();
    await userEvent.keyboard('{Escape}');
    await expect(b).toHaveFocus();
    await expect(b).toHaveAttribute('aria-expanded', 'false');
  },
};

/**
 * Edited, the mark says so where it is seen and heard, and the explanation's
 * heading says who made it.
 */
export const EditedSaysSo: Story = {
  args: { isEdited: true },
  play: async ({ canvas }) => {
    const b = button(canvas);
    await expect(b).toHaveAccessibleName('AI, Edited: About this summary');
    await expect(b).toHaveTextContent('AIEdited');
    await userEvent.click(b);
    const bubble = document.getElementById(b.getAttribute('aria-controls')!)!;
    await expect(bubble).toHaveTextContent(
      /^Generated by AI, edited by a person/,
    );
  },
};

/** Every string translates, and the name follows the translated mark. */
export const TheWordsTranslate: Story = {
  args: {
    'aria-label': 'À propos de ce résumé',
    isEdited: true,
    labels: {
      mark: 'IA',
      edited: 'Modifié',
      title: 'Généré par IA',
      editedTitle: 'Généré par IA, modifié par une personne',
    },
  },
  play: async ({ canvas }) => {
    const b = canvas.getByRole('button', { name: /^IA/ });
    await expect(b).toHaveAccessibleName('IA, Modifié: À propos de ce résumé');
    await userEvent.click(b);
    const bubble = document.getElementById(b.getAttribute('aria-controls')!)!;
    await expect(bubble).toHaveTextContent(/^Généré par IA, modifié/);
  },
};

/** Both sizes are a 24px target, however small the mark is drawn. */
export const TargetMeetsTheMinimum: Story = {
  args: { size: 'sm' },
  play: async ({ canvas }) => {
    const b = button(canvas);
    await expect(Math.round(b.getBoundingClientRect().height)).toBe(20);
    const after = getComputedStyle(b, '::after');
    await expect(after.content).not.toBe('none');
    // The pseudo-element reaches 2px past the mark on both sides.
    await expect(after.top).toBe('-2px');
    await expect(after.bottom).toBe('-2px');
    await expect(b.getBoundingClientRect().width).toBeGreaterThanOrEqual(24);
  },
};

/** At md the mark itself is the 24px target, and it keeps the line's height. */
export const MediumIsTheTarget: Story = {
  play: async ({ canvas }) => {
    const b = button(canvas);
    await expect(Math.round(b.getBoundingClientRect().height)).toBe(24);
    await expect(getComputedStyle(b).marginTop).toBe('-4px');
  },
};

/** The mark is the primary role, not a status colour. */
export const TheMarkIsNotAStatus: Story = {
  play: async ({ canvas }) => {
    const b = button(canvas);
    const probe = document.createElement('span');
    document.body.append(probe);
    const colour = (token: string) => {
      probe.style.color = `var(${token})`;
      return getComputedStyle(probe).color;
    };
    await expect(getComputedStyle(b).color).toBe(colour('--text-primary'));
    await expect(getComputedStyle(b).color).not.toBe(
      colour('--text-information'),
    );
    probe.remove();
  },
};
